/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_pojet_cadenas_elias;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane; // <--- AJOUTER CET IMPORT
import javax.swing.JTextArea;

/**
 *
 * @author eradi
 */
public class interface_jeu extends javax.swing.JFrame {
    private JeuCadenas jeu = new JeuCadenas();

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interface_jeu.class.getName());
    
    /**
     * Creates new form interface_jeu
     */
    public interface_jeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        txtHistorique = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Trouver le bon code en moins de 5 tentatives ");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 14, -1, -1));

        up_chiffre_1.setText("/\\");
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 48, -1, -1));

            up_chiffre_2.setText("/\\");
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 48, -1, -1));

                up_chiffre_3.setText("/\\");
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 48, -1, -1));

                    up_chiffre_4.setText("/\\");
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 48, -1, -1));

                        texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        texte_chiffre_0.setText("    0");
                        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 97, 72, -1));

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        texte_chiffre_1.setText(" 0");
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 97, 38, -1));

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        texte_chiffre_2.setText("0");
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 97, 28, -1));

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        texte_chiffre_3.setText("0");
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 89, -1, 56));

                        down_chiffre_1.setText("\\/");
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 157, -1, -1));

                        down_chiffre_2.setText("\\/");
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 157, -1, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 157, -1, -1));

                        down_chiffre_4.setText("\\/");
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 157, -1, -1));

                        bouton_tester.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
                        bouton_tester.setText("Tester");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 105, -1, -1));

                        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts :");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 215, 155, -1));

                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 215, 37, -1));

                        texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres hauts :");
                        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 249, 155, -1));

                        texte_nb_chiffres_haut.setText("0");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 255, 43, -1));

                        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 283, -1, -1));

                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 283, 43, -1));

                        texte_score.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
                        texte_score.setText("    0 sur 4 ");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 249, 118, 59));

                        texte_tentatives.setText("Tentatives:");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 215, 64, -1));

                        bouton_recommencer.setText("Recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 332, -1, -1));
                        getContentPane().add(txtHistorique, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 100, 90));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
try {
     
        List<Integer> texte_tentatives = new ArrayList<>();
        texte_tentatives.add(Integer.parseInt(texte_chiffre_0.getText()));
       texte_tentatives.add(Integer.parseInt(texte_chiffre_1.getText()));
        texte_tentatives.add(Integer.parseInt(texte_chiffre_2.getText()));
        texte_tentatives.add(Integer.parseInt(texte_chiffre_3.getText()));

      
        int[] resultat = jeu.testerCombinaison(texte_tentatives);

        // 3 - Afficher les résultats
        texte_lbl_nb_chiffres_exacts.setText("Corrects : " + resultat[0]);
      texte_lbl_nb_chiffres_bas.setText("Trop bas : " + resultat[1]);
        texte_lbl_nb_chiffres_haut.setText("Trop hauts : " + resultat[2]);

       
        txtHistorique.append(
            texte_tentatives.toString() +
            " → bons: " + resultat[0] +
            ", bas: " + resultat[1] +
            ", hauts: " + resultat[2] + "\n"
        );

     
        if (jeu.isGagne()) {
            JOptionPane.showMessageDialog(this, "Bravo ! Vous avez gagné !");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Veuillez entrer des chiffres valides !");
    }      
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
 
    jeu.reinitialiser();

    
    texte_chiffre_0.setText("");
    texte_chiffre_1.setText("");
   texte_chiffre_2.setText("");
    texte_chiffre_3.setText("");

    // Réinitialiser les labels
    texte_lbl_nb_chiffres_exacts.setText("Corrects : 0");
    texte_lbl_nb_chiffres_bas.setText("Trop bas : 0");
    texte_lbl_nb_chiffres_haut.setText("Trop hauts : 0");

   
    txtHistorique.setText("");

    JOptionPane.showMessageDialog(this, "Nouvelle partie !");        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interface_jeu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JScrollPane txtHistorique;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
