/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eradi
 */
import javax.swing.*;
import java.awt.*;
import miniprojet_cadenas_radibenjelloun.ResultatEssai;
public class Interface_jeu extends javax.swing.JFrame {
    private JTextField txt_essai;
    private JButton btn_valider;
    private JTextArea zone_resultats;
    private JLabel lbl_essaisRestants;

    private CadenasGame game;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface_jeu.class.getName());

    /**
     * @param game
     */
    public Interface_jeu(CadenasGame game) {
        this.game = game;
         setTitle("Jeu Cadenas - Mastermind");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // --- Haut : zone de saisie ---
        JPanel panelHaut = new JPanel();
        txt_essai = new JTextField(5);
        btn_valider = new JButton("Valider");
        panelHaut.add(new JLabel("Essai (4 chiffres) :"));
        panelHaut.add(txt_essai);
        panelHaut.add(btn_valider);

        // --- Centre : zone des résultats ---
        zone_resultats = new JTextArea();
        zone_resultats.setEditable(false);
        JScrollPane scroll = new JScrollPane(zone_resultats);

        // --- Bas : essais restants ---
        lbl_essaisRestants = new JLabel("Essais restants : " + game.getEssaisRestants());
        lbl_essaisRestants.setHorizontalAlignment(SwingConstants.CENTER);

        add(panelHaut, BorderLayout.NORTH);
        add(scroll, BorderLayout.CENTER);
        add(lbl_essaisRestants, BorderLayout.SOUTH);

        // Action du bouton
        btn_valider.addActionListener(e -> traiterEssai());

        setVisible(true);
        // Dans le constructeur de Interface_jeu
// ...
// Action du bouton
btn_valider.addActionListener(e -> traiterEssai());

// setVisible(true);  <-- RETIRER CETTE LIGNE !

// Si vous utilisez ma version corrigée :
// }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_ = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl__nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl__nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl__nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });

            up_chiffre_2.setText("/\\");

                up_chiffre_3.setText("/\\");

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });

                        texte_chiffre_0.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        texte_chiffre_0.setText("NB1");

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        texte_chiffre_1.setText("NB2");

                        texte_chiffre_.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        texte_chiffre_.setText("NB3");

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        texte_chiffre_3.setText("NB4");

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });

                        down_chiffre_2.setText("\\/");

                        down_chiffre_3.setText("\\/");

                        down_chiffre_4.setText("\\/");

                        bouton_tester.setText("Tester");

                        texte_lbl__nb_chiffres_exacts.setText("Nombre de chiffres exactes :");

                        texte_nb_chiffres_exacts.setText("0");

                        texte_lbl__nb_chiffres_haut.setText("Nombre de chiffres trop hauts:");

                        texte_nb_chiffres_haut.setText("0");

                        texte_lbl__nb_chiffres_bas.setText("Nombre de chiffres trop bas:");

                        texte_nb_chiffres_bas.setText("0");

                        texte_score.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        texte_score.setText("0 sur 5");

                        texte_tentatives.setText("Tentatives");

                        bouton_recommencer.setText("Recommencer");

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(texte_chiffre_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(up_chiffre_1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(up_chiffre_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(up_chiffre_3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(up_chiffre_4)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(texte_chiffre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(texte_chiffre_, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(texte_chiffre_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bouton_tester))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(down_chiffre_4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(down_chiffre_3)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(down_chiffre_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(down_chiffre_1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 153, Short.MAX_VALUE)
                                                .addComponent(texte_tentatives)))
                                        .addGap(51, 51, 51))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(texte_lbl__nb_chiffres_haut)
                                            .addComponent(texte_lbl__nb_chiffres_exacts))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(texte_nb_chiffres_haut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(texte_nb_chiffres_exacts, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(texte_score, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(texte_lbl__nb_chiffres_bas)
                                        .addGap(18, 18, 18)
                                        .addComponent(texte_nb_chiffres_bas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bouton_recommencer)
                                        .addGap(6, 6, 6)))
                                .addContainerGap())
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(up_chiffre_1)
                                    .addComponent(up_chiffre_2)
                                    .addComponent(up_chiffre_3)
                                    .addComponent(up_chiffre_4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(texte_chiffre_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(texte_chiffre_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(texte_chiffre_1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(texte_chiffre_0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(bouton_tester)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(down_chiffre_4)
                                    .addComponent(down_chiffre_3)
                                    .addComponent(down_chiffre_2)
                                    .addComponent(down_chiffre_1))
                                .addGap(29, 29, 29)
                                .addComponent(texte_tentatives)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(texte_nb_chiffres_exacts)
                                    .addComponent(texte_lbl__nb_chiffres_exacts))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(texte_lbl__nb_chiffres_haut)
                                    .addComponent(texte_nb_chiffres_haut)
                                    .addComponent(texte_score, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(texte_lbl__nb_chiffres_bas)
                                    .addComponent(texte_nb_chiffres_bas)
                                    .addComponent(bouton_recommencer))
                                .addGap(51, 51, 51))
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Le code de lancement NE CONTIENT PAS la déclaration du constructeur !
        final CadenasGame jeu = new CadenasGame();
        
        // ... code Look and Feel ...
        
        java.awt.EventQueue.invokeLater(() -> {
            // Appel du constructeur :
            new Interface_jeu(jeu).setVisible(true);
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel texte_chiffre_;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_lbl__nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl__nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl__nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables

    private int[] lireChiffresDepuisInterface() {
         
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void afficherResultat(Resultat r) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void traiterEssai() {
        String essai = txt_essai.getText();

        if (essai.length() != 4 || !essai.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer 4 chiffres.");
            return;
        
        
    }
        ResultatEssai r = game.verifier(essai);
        zone_resultats.append(
                essai + " → Exact: " + r.exact + 
                ", Trop haut: " + r.tropHaut +
                ", Trop bas: " + r.tropBas + "\n"
        );

        lbl_essaisRestants.setText("Essais restants : " + r.essaisRestants);

        if (r.exact == 4) {
            JOptionPane.showMessageDialog(this, "Bravo ! Vous avez trouvé !");
            System.exit(0);
        }
        if (r.essaisRestants == 0) {
            JOptionPane.showMessageDialog(this, "Perdu ! Plus d'essais.");
            System.exit(0);
        }
        txt_essai.setText("");
}
    
}
