/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eradi
 */
public class Interface_jeu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface_jeu.class.getName());

    /**
     * Creates new form Interface_jeu
     */
    public Interface_jeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        fleche_1 = new javax.swing.JButton();
        Fleche_2 = new javax.swing.JButton();
        Fleche_3 = new javax.swing.JButton();
        Fleche_4 = new javax.swing.JButton();
        Fleche_8 = new javax.swing.JButton();
        Fleche_7 = new javax.swing.JButton();
        Fleche_6 = new javax.swing.JButton();
        Fleche_5 = new javax.swing.JButton();
        nb_variable1 = new javax.swing.JLabel();
        nb_variable2 = new javax.swing.JLabel();
        nb_variable3 = new javax.swing.JLabel();
        nb_variable4 = new javax.swing.JLabel();
        nb_affichage_exactes = new javax.swing.JLabel();
        nb_affichage_hauts = new javax.swing.JLabel();
        nb_affichage_bas = new javax.swing.JLabel();
        affichage_exactes = new javax.swing.JLabel();
        nb_haut = new javax.swing.JLabel();
        nb_bas = new javax.swing.JLabel();
        btn_tester = new javax.swing.JButton();
        Tentavives = new javax.swing.JLabel();
        nb_valide = new javax.swing.JLabel();
        btn_recommencer = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fleche_1.setText("/\\");
            fleche_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    fleche_1ActionPerformed(evt);
                }
            });

            Fleche_2.setText("/\\");

                Fleche_3.setText("/\\");

                    Fleche_4.setText("/\\");

                        Fleche_8.setText("\\/");

                        Fleche_7.setText("\\/");

                        Fleche_6.setText("\\/");

                        Fleche_5.setText("\\/");

                        nb_variable1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        nb_variable1.setText("NB1");

                        nb_variable2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        nb_variable2.setText("NB2");

                        nb_variable3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        nb_variable3.setText("NB3");

                        nb_variable4.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        nb_variable4.setText("NB4");

                        nb_affichage_exactes.setText("Nombre de chiffres exactes :");

                        nb_affichage_hauts.setText("Nombre de chiffres trop hauts:");

                        nb_affichage_bas.setText("Nombre de chiffres trop bas:");

                        affichage_exactes.setText("0");

                        nb_haut.setText("0");

                        nb_bas.setText("0");

                        btn_tester.setText("Tester");

                        Tentavives.setText("Tentatives");

                        nb_valide.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
                        nb_valide.setText("0 sur 5");

                        btn_recommencer.setText("Recommencer");

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nb_variable1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fleche_1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(Fleche_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Fleche_3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Fleche_4)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(nb_variable2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(nb_variable3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nb_variable4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_tester))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Fleche_5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Fleche_6)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Fleche_7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Fleche_8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 153, Short.MAX_VALUE)
                                                .addComponent(Tentavives)))
                                        .addGap(51, 51, 51))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nb_affichage_hauts)
                                            .addComponent(nb_affichage_exactes))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nb_haut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(affichage_exactes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nb_valide, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nb_affichage_bas)
                                        .addGap(18, 18, 18)
                                        .addComponent(nb_bas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_recommencer)
                                        .addGap(6, 6, 6)))
                                .addContainerGap())
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fleche_1)
                                    .addComponent(Fleche_2)
                                    .addComponent(Fleche_3)
                                    .addComponent(Fleche_4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nb_variable4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nb_variable3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nb_variable2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nb_variable1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btn_tester)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Fleche_5)
                                    .addComponent(Fleche_6)
                                    .addComponent(Fleche_7)
                                    .addComponent(Fleche_8))
                                .addGap(29, 29, 29)
                                .addComponent(Tentavives)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(affichage_exactes)
                                    .addComponent(nb_affichage_exactes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nb_affichage_hauts)
                                    .addComponent(nb_haut)
                                    .addComponent(nb_valide, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nb_affichage_bas)
                                    .addComponent(nb_bas)
                                    .addComponent(btn_recommencer))
                                .addGap(51, 51, 51))
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void fleche_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fleche_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fleche_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface_jeu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fleche_2;
    private javax.swing.JButton Fleche_3;
    private javax.swing.JButton Fleche_4;
    private javax.swing.JButton Fleche_5;
    private javax.swing.JButton Fleche_6;
    private javax.swing.JButton Fleche_7;
    private javax.swing.JButton Fleche_8;
    private javax.swing.JLabel Tentavives;
    private javax.swing.JLabel affichage_exactes;
    private javax.swing.JButton btn_recommencer;
    private javax.swing.JButton btn_tester;
    private javax.swing.JButton fleche_1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel nb_affichage_bas;
    private javax.swing.JLabel nb_affichage_exactes;
    private javax.swing.JLabel nb_affichage_hauts;
    private javax.swing.JLabel nb_bas;
    private javax.swing.JLabel nb_haut;
    private javax.swing.JLabel nb_valide;
    private javax.swing.JLabel nb_variable1;
    private javax.swing.JLabel nb_variable2;
    private javax.swing.JLabel nb_variable3;
    private javax.swing.JLabel nb_variable4;
    // End of variables declaration//GEN-END:variables
}
