
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eradi
 */
public class interface_Elias extends javax.swing.JFrame {
    private ArrayList<Question> listeQuestions;
private int indexQuestionCourante = 0;
private int score = 0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interface_Elias.class.getName());
    int compteur=0;

    /**
     * Creates new form interface_Elias
     */
    public interface_Elias() {
        initComponents();//constructeur
       // FenetreQuiz.java (extrait du constructeur)

    listeQuestions = new ArrayList<>();

    listeQuestions.add(
        new Question("Combien font 1 + 1 ?", "1", "2", "3", "4", 2)
    );
    afficherQuestionCourante();

    
}
    private void afficherQuestionCourante() {
        Question q = listeQuestions.get(indexQuestionCourante);
lblQuestion.setText(q.getIntitule());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        btnSuivant = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestion.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblQuestion.setText("lblQuestion");
        getContentPane().add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 105, -1));

        btnRep1.setText("Réponse 1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 30));

        lblFeedback.setText("jLabel1");
        getContentPane().add(lblFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        btnSuivant.setText("Question suivante");
        getContentPane().add(btnSuivant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        btnRep2.setText("Réponse 2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 90, 30));

        btnRep3.setText("Réponse 3");
        getContentPane().add(btnRep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 90, 30));

        btnRep4.setText("Réponse 4");
        getContentPane().add(btnRep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRep2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interface_Elias().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}
